create table if not exists public.event_leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  name text not null,
  email text not null,
  brand text,
  event_type text not null,
  event_date date,
  attendees text,
  message text not null
);

create table if not exists public.marketing_leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  name text not null,
  email text not null,
  brand text,
  marketing_goals text not null,
  budget text,
  message text not null
);
